/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/edit-header copy 2.vue')['default']
    3: typeof import('./src/components/edit-header copy 3.vue')['default']
    4: typeof import('./src/components/edit-header copy 4.vue')['default']
    ConfigInput: typeof import('./src/components/config/config-input.vue')['default']
    copy: typeof import('./src/components/edit/edit-render copy.vue')['default']
    EditBlock: typeof import('./src/components/edit/edit-block.vue')['default']
    EditBlockDrag: typeof import('./src/components/edit/edit-block-drag.vue')['default']
    EditConfig: typeof import('./src/components/edit/edit-config.vue')['default']
    EditConfigBlock: typeof import('./src/components/edit/edit-config-block.vue')['default']
    EditConfigPage: typeof import('./src/components/edit/edit-config-page.vue')['default']
    EditConfigRender: typeof import('./src/components/edit/edit-config-render.vue')['default']
    EditHeader: typeof import('./src/components/edit/edit-header.vue')['default']
    EditRender: typeof import('./src/components/edit/edit-render.vue')['default']
    EditRenderDrag: typeof import('./src/components/edit/edit-render-drag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VIcon: typeof import('./src/components/base/v-icon.vue')['default']
    VIconTooltip: typeof import('./src/components/base/v-icon-tooltip.vue')['default']
    VInconTooltip: typeof import('./src/components/base/v-incon-tooltip.vue')['default']
    VSelect: typeof import('./src/components/base/v-select.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
